name: Test Tagging Release
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - Release v*.*.*.*
  push:
    tags:
      - 'v*' #v*.*.*.*

  workflow_dispatch:
    inputs:
      environment:
        description: 'Re-Run Action'
        required: true
        default: 'Re-run Action'
        type: choice
        options:
          - Re-Run Action

jobs:
  label_and_notify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22.2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0
    

  create_release:
    runs-on: ubuntu-latest
    needs: label_and_notify
    permissions:
      actions: write
      attestations: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      issues: write
      pages: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Echo Tag 
        run: echo ${{ github.ref_name }}  ${{ github.ref }}
        
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref_name}}
          release_name: ${{ github.ref_name}}
          body: |
            Changes in this Release
            - First Change
            - Second Change          
          draft: false
          prerelease: false
